# Generated by Django 3.0.8 on 2020-07-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='balance',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='balance',
        ),
    ]
